---
# handlers/main.yml - handlers for homescreen role

- name: Update pkg catalog
  ansible.builtin.command: pkg update

- name: Restart homescreen
  ansible.builtin.service:
    name: homescreen
    state: restarted
  when: ansible_facts.services['homescreen'] is defined

- name: Start homescreen
  ansible.builtin.service:
    name: homescreen
    state: started
