---
# handlers/main.yml - handlers for homescreen role

- name: Update pkg catalog
  ansible.builtin.command: pkg update
  tags: [homescreen, homescreen.repo]

- name: Restart homescreen
  ansible.builtin.service:
    name: homescreen
    state: restarted
  tags: [homescreen, homescreen.service]

- name: Start homescreen
  ansible.builtin.service:
    name: homescreen
    state: started
  tags: [homescreen, homescreen.service]
